import type { ItemGenerator } from "./types";
import { ELA_GENERATORS } from "./generators/ela-registry";
import {
  additionWithinHundred,
  subtractionWithinHundred,
} from "./generators/g2-addition";
import {
  compareNumbers,
  expandedFormItem,
  roundToTen,
  wordForm,
} from "./generators/g2-place-value";
import { tellTimeToFiveMinutes } from "./generators/g2-time";
import { solidAttributes, solidRealWorld } from "./generators/g2-solids";
import {
  linesOfSymmetry,
  nameTheShape,
  perimeter,
  shapeSides,
} from "./generators/g2-shapes";
import {
  evenOdd,
  factsToTwenty,
  repeatedAddition,
  tenMoreLess,
  trueOrFalse,
  unknownNumber,
} from "./generators/g2-algebra";
import {
  countMoney,
  lengthDifference,
  partitionShapes,
  readData,
} from "./generators/g2-measurement";
import {
  countSequence,
  g1Compare,
  g1ExpandedForm,
  g1FactsToTen,
  g1OneTenMoreLess,
  g1SumsToTwenty,
  g1TensAndOnes,
  g1TwoDigitMinusOne,
  g1TwoDigitPlusOne,
  g1WordForm,
} from "./generators/g1-number";
import {
  g1AddThree,
  g1CoinValue,
  g1ComposeShapes,
  g1CountCoins,
  g1HalvesFourths,
  g1MeasureLength,
  g1MissingAddend,
  g1OrderLengths,
  g1Pictograph,
  g1ShapeFromAttributes,
  g1Tallies,
  g1TellTime,
  g1TrueFalse,
  g1UnknownNumber,
  g1WordProblem,
} from "./generators/g1-rest";
import {
  g2BuildGraph,
  g2ChooseUnit,
  g2LengthProblem,
  g2PartitionTwoWays,
  g2PerimeterUnits,
  g2ThreeDigit,
  g2TwoStepProblem,
} from "./generators/g2-gaps";
import {
  g3ComposeFourDigit,
  g3Compare,
  g3FactsAndDivision,
  g3MultiDigit,
  g3MultiplicationMeaning,
  g3MultiplyByTens,
  g3Round,
  g3WordForm,
} from "./generators/g3-number";
import {
  g3CompareFractions,
  g3EquivalentFractions,
  g3FractionWords,
  g3RepeatedUnit,
  g3UnitFraction,
} from "./generators/g3-fractions";
import {
  g3AreaByCounting,
  g3AreaFormula,
  g3ChooseTool,
  g3CompositeArea,
  g3DataProblem,
  g3Distributive,
  g3ElapsedTime,
  g3EvenOdd,
  g3FourOpProblem,
  g3LinesAndRays,
  g3MeasureProblem,
  g3MissingFactor,
  g3Multiples,
  g3Patterns,
  g3PerimeterArea,
  g3Quadrilaterals,
  g3ScaledGraph,
  g3Symmetry,
  g3TellTimeMinute,
  g3TrueFalseTimes,
  g3UnknownFactor,
} from "./generators/g3-rest";
import {
  g4CompareDecimals,
  g4CompareWhole,
  g4DecimalAddSub,
  g4Divide,
  g4Estimate,
  g4Facts,
  g4MultiplyLarge,
  g4MultiplyTwoByTwo,
  g4PlaceValueShift,
  g4Round,
  g4TenthMoreLess,
  g4WordForm,
} from "./generators/g4-number";
import {
  g4AddAngles,
  g4AddLike,
  g4AddTenthHundredth,
  g4ChooseTool,
  g4ClassifyAngle,
  g4CompareUnlike,
  g4Convert,
  g4DataProblem,
  g4Decompose,
  g4DistanceTime,
  g4Equivalent,
  g4FractionProblem,
  g4FractionTimesProblem,
  g4FractionTimesWhole,
  g4FractionToDecimal,
  g4LinePlot,
  g4ModeMedianRange,
  g4Money,
  g4Pattern,
  g4PrimeComposite,
  g4RemainderProblem,
  g4SamePerimeter,
  g4TenthsToHundredths,
  g4TrueFalse,
  g4UnknownAngle,
  g4UnknownSide,
  g4WriteEquation,
} from "./generators/g4-rest";
import {
  g5CompareDecimals,
  g5DecimalAddSub,
  g5DecimalWords,
  g5DecomposeDecimal,
  g5DivideTwoDigit,
  g5EstimateDecimal,
  g5MultiplyLarge,
  g5PlaceValue,
  g5RoundDecimal,
  g5TimesPointOne,
} from "./generators/g5-number";
import {
  g5AddUnlike,
  g5Averages,
  g5Classify,
  g5Convert,
  g5CoordinateProblem,
  g5Coordinates,
  g5DivideFractionProblem,
  g5DivideUnitFraction,
  g5DivisionAsFraction,
  g5FractionProblem,
  g5FractionalArea,
  g5LineGraph,
  g5Money,
  g5MultiStep,
  g5MultiplyFractions,
  g5OrderOfOperations,
  g5PatternRule,
  g5ProductSize,
  g5RuleTable,
  g5Solids,
  g5TranslateExpression,
  g5TrueFalse,
  g5VolumeCount,
  g5VolumeFormula,
  g5VolumeUnknown,
  g5WriteEquation,
} from "./generators/g5-rest";
import {
  g6AbsoluteProblem,
  g6AbsoluteValue,
  g6AddIntegers,
  g6CompareRational,
  g6DecimalMulDiv,
  g6Exponents,
  g6FactorSum,
  g6FractionDecimalPercent,
  g6FractionMulDiv,
  g6GcfLcm,
  g6MixedProblem,
  g6MulIntegers,
  g6Opposites,
  g6PrimeFactors,
} from "./generators/g6-number";
import {
  g6Averages,
  g6BoxPlot,
  g6ChangeEffect,
  g6CompositeArea,
  g6Distance,
  g6Distribution,
  g6EquivalentExpressions,
  g6Evaluate,
  g6Histogram,
  g6Inequality,
  g6OneStepAdd,
  g6OneStepMul,
  g6Percent,
  g6PlottedRectangle,
  g6Quadrants,
  g6RateProblem,
  g6Ratio,
  g6RatioTable,
  g6StatisticalQuestion,
  g6SurfaceArea,
  g6TranslateAlgebra,
  g6TriangleArea,
  g6UnitRate,
  g6UnknownDecimal,
  g6Volume,
  g6WhichValue,
} from "./generators/g6-rest";

/**
 * Every generator in the platform. Keyed lookup so a stored attempt can be
 * replayed years later from nothing but a template key and a seed.
 */
export const GENERATORS: ItemGenerator[] = [
  /* Grade 1 */
  countSequence,
  g1WordForm,
  g1ExpandedForm,
  g1TensAndOnes,
  g1Compare,
  g1FactsToTen,
  g1SumsToTwenty,
  g1OneTenMoreLess,
  g1TwoDigitPlusOne,
  g1TwoDigitMinusOne,
  g1HalvesFourths,
  g1AddThree,
  g1WordProblem,
  g1MissingAddend,
  g1TrueFalse,
  g1UnknownNumber,
  g1MeasureLength,
  g1OrderLengths,
  g1TellTime,
  g1CoinValue,
  g1CountCoins,
  g1ShapeFromAttributes,
  g1ComposeShapes,
  g1Tallies,
  g1Pictograph,

  /* Grade 2 */
  additionWithinHundred,
  g2ThreeDigit,
  g2PartitionTwoWays,
  g2TwoStepProblem,
  g2ChooseUnit,
  g2LengthProblem,
  g2PerimeterUnits,
  g2BuildGraph,
  subtractionWithinHundred,
  wordForm,
  expandedFormItem,
  roundToTen,
  compareNumbers,
  tellTimeToFiveMinutes,
  solidAttributes,
  solidRealWorld,
  shapeSides,
  nameTheShape,
  linesOfSymmetry,
  perimeter,
  evenOdd,
  repeatedAddition,
  trueOrFalse,
  unknownNumber,
  tenMoreLess,
  factsToTwenty,
  countMoney,
  lengthDifference,
  readData,
  partitionShapes,

  /* Grade 3 */
  g3WordForm,
  g3ComposeFourDigit,
  g3Compare,
  g3Round,
  g3MultiDigit,
  g3MultiplicationMeaning,
  g3MultiplyByTens,
  g3FactsAndDivision,
  g3UnitFraction,
  g3RepeatedUnit,
  g3FractionWords,
  g3CompareFractions,
  g3EquivalentFractions,
  g3Distributive,
  g3FourOpProblem,
  g3MissingFactor,
  g3TrueFalseTimes,
  g3UnknownFactor,
  g3EvenOdd,
  g3Multiples,
  g3Patterns,
  g3ChooseTool,
  g3MeasureProblem,
  g3TellTimeMinute,
  g3ElapsedTime,
  g3LinesAndRays,
  g3Quadrilaterals,
  g3Symmetry,
  g3AreaByCounting,
  g3AreaFormula,
  g3PerimeterArea,
  g3CompositeArea,
  g3ScaledGraph,
  g3DataProblem,

  /* Grade 4 */
  g4PlaceValueShift,
  g4WordForm,
  g4CompareWhole,
  g4Round,
  g4CompareDecimals,
  g4Facts,
  g4MultiplyLarge,
  g4MultiplyTwoByTwo,
  g4Divide,
  g4Estimate,
  g4TenthMoreLess,
  g4DecimalAddSub,
  g4TenthsToHundredths,
  g4FractionToDecimal,
  g4Equivalent,
  g4CompareUnlike,
  g4Decompose,
  g4AddLike,
  g4AddTenthHundredth,
  g4FractionTimesWhole,
  g4RemainderProblem,
  g4FractionProblem,
  g4FractionTimesProblem,
  g4TrueFalse,
  g4WriteEquation,
  g4PrimeComposite,
  g4Pattern,
  g4ChooseTool,
  g4Convert,
  g4DistanceTime,
  g4Money,
  g4ClassifyAngle,
  g4AddAngles,
  g4UnknownAngle,
  g4UnknownSide,
  g4SamePerimeter,
  g4LinePlot,
  g4ModeMedianRange,
  g4DataProblem,

  /* Grade 5 */
  g5PlaceValue,
  g5DecimalWords,
  g5DecomposeDecimal,
  g5CompareDecimals,
  g5RoundDecimal,
  g5MultiplyLarge,
  g5DivideTwoDigit,
  g5DecimalAddSub,
  g5EstimateDecimal,
  g5TimesPointOne,
  g5DivisionAsFraction,
  g5AddUnlike,
  g5MultiplyFractions,
  g5ProductSize,
  g5DivideUnitFraction,
  g5MultiStep,
  g5FractionProblem,
  g5DivideFractionProblem,
  g5TranslateExpression,
  g5OrderOfOperations,
  g5TrueFalse,
  g5WriteEquation,
  g5PatternRule,
  g5RuleTable,
  g5Convert,
  g5Money,
  g5Classify,
  g5Solids,
  g5FractionalArea,
  g5VolumeCount,
  g5VolumeFormula,
  g5VolumeUnknown,
  g5Coordinates,
  g5CoordinateProblem,
  g5LineGraph,
  g5Averages,

  /* Grade 6 */
  g6CompareRational,
  g6Opposites,
  g6AbsoluteValue,
  g6AbsoluteProblem,
  g6DecimalMulDiv,
  g6FractionMulDiv,
  g6MixedProblem,
  g6GcfLcm,
  g6FactorSum,
  g6Exponents,
  g6PrimeFactors,
  g6FractionDecimalPercent,
  g6AddIntegers,
  g6MulIntegers,
  g6TranslateAlgebra,
  g6Inequality,
  g6Evaluate,
  g6EquivalentExpressions,
  g6WhichValue,
  g6OneStepAdd,
  g6OneStepMul,
  g6UnknownDecimal,
  g6Ratio,
  g6UnitRate,
  g6RatioTable,
  g6Percent,
  g6RateProblem,
  g6Quadrants,
  g6Distance,
  g6PlottedRectangle,
  g6TriangleArea,
  g6CompositeArea,
  g6Volume,
  g6SurfaceArea,
  g6StatisticalQuestion,
  g6Averages,
  g6BoxPlot,
  g6Distribution,
  g6Histogram,
  g6ChangeEffect,

  /*
   * English Language Arts.
   *
   * Built from a table rather than written out one by one; see
   * generators/ela-registry.ts for why.
   */
  ...ELA_GENERATORS,
];

const BY_KEY = new Map(GENERATORS.map((g) => [g.key, g]));

export function getGenerator(key: string): ItemGenerator {
  const g = BY_KEY.get(key);
  if (!g) throw new Error(`Unknown generator: ${key}`);
  return g;
}

export function generatorsForBenchmark(benchmark: string): ItemGenerator[] {
  return GENERATORS.filter((g) => g.benchmark === benchmark);
}

export function generatorsForSkill(skillSlug: string): ItemGenerator[] {
  return GENERATORS.filter((g) => g.skillSlug === skillSlug);
}

/** Benchmarks that currently have at least one generator behind them. */
export function coveredBenchmarks(): string[] {
  return [...new Set(GENERATORS.map((g) => g.benchmark))].sort();
}
